var wms_layers = [];


        var lyr_OpenStreetMap_0 = new ol.layer.Tile({
            'title': 'OpenStreetMap',
            'type':'base',
            'opacity': 1.000000,
            
            
            source: new ol.source.XYZ({
            attributions: ' ',
                url: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png'
            })
        });
var format_Localauthorityname_1 = new ol.format.GeoJSON();
var features_Localauthorityname_1 = format_Localauthorityname_1.readFeatures(json_Localauthorityname_1, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Localauthorityname_1 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Localauthorityname_1.addFeatures(features_Localauthorityname_1);
var lyr_Localauthorityname_1 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Localauthorityname_1, 
                style: style_Localauthorityname_1,
                popuplayertitle: 'Local authority name',
                interactive: true,
                title: '<img src="styles/legend/Localauthorityname_1.png" /> Local authority name'
            });
var format_Economicallyactive1664Unemployedn_2 = new ol.format.GeoJSON();
var features_Economicallyactive1664Unemployedn_2 = format_Economicallyactive1664Unemployedn_2.readFeatures(json_Economicallyactive1664Unemployedn_2, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Economicallyactive1664Unemployedn_2 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Economicallyactive1664Unemployedn_2.addFeatures(features_Economicallyactive1664Unemployedn_2);
var lyr_Economicallyactive1664Unemployedn_2 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Economicallyactive1664Unemployedn_2, 
                style: style_Economicallyactive1664Unemployedn_2,
                popuplayertitle: 'Economically active - 16-64 Unemployed (n)',
                interactive: true,
    title: 'Economically active - 16-64 Unemployed (n)<br />\
    <img src="styles/legend/Economicallyactive1664Unemployedn_2_0.png" /> 1800 - 1800<br />\
    <img src="styles/legend/Economicallyactive1664Unemployedn_2_1.png" /> 1800 - 3400<br />\
    <img src="styles/legend/Economicallyactive1664Unemployedn_2_2.png" /> 3400 - 5300<br />\
    <img src="styles/legend/Economicallyactive1664Unemployedn_2_3.png" /> 5300 - 8400<br />\
    <img src="styles/legend/Economicallyactive1664Unemployedn_2_4.png" /> 8400 - 10200<br />' });
var format_Economicallyactive1664Unemployed_3 = new ol.format.GeoJSON();
var features_Economicallyactive1664Unemployed_3 = format_Economicallyactive1664Unemployed_3.readFeatures(json_Economicallyactive1664Unemployed_3, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Economicallyactive1664Unemployed_3 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Economicallyactive1664Unemployed_3.addFeatures(features_Economicallyactive1664Unemployed_3);
var lyr_Economicallyactive1664Unemployed_3 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Economicallyactive1664Unemployed_3, 
                style: style_Economicallyactive1664Unemployed_3,
                popuplayertitle: 'Economically active - 16-64 Unemployed %',
                interactive: true,
    title: 'Economically active - 16-64 Unemployed %<br />\
    <img src="styles/legend/Economicallyactive1664Unemployed_3_0.png" /> 1.9 - 1.9<br />\
    <img src="styles/legend/Economicallyactive1664Unemployed_3_1.png" /> 1.9 - 2.7<br />\
    <img src="styles/legend/Economicallyactive1664Unemployed_3_2.png" /> 2.7 - 3.6<br />\
    <img src="styles/legend/Economicallyactive1664Unemployed_3_3.png" /> 3.6 - 5<br />\
    <img src="styles/legend/Economicallyactive1664Unemployed_3_4.png" /> 5 - 6.5<br />' });
var format_Economicallyinactive1664Alln_4 = new ol.format.GeoJSON();
var features_Economicallyinactive1664Alln_4 = format_Economicallyinactive1664Alln_4.readFeatures(json_Economicallyinactive1664Alln_4, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Economicallyinactive1664Alln_4 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Economicallyinactive1664Alln_4.addFeatures(features_Economicallyinactive1664Alln_4);
var lyr_Economicallyinactive1664Alln_4 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Economicallyinactive1664Alln_4, 
                style: style_Economicallyinactive1664Alln_4,
                popuplayertitle: 'Economically inactive - 16-64 All (n)',
                interactive: true,
    title: 'Economically inactive - 16-64 All (n)<br />\
    <img src="styles/legend/Economicallyinactive1664Alln_4_0.png" /> 13100 - 13100<br />\
    <img src="styles/legend/Economicallyinactive1664Alln_4_1.png" /> 13100 - 24600<br />\
    <img src="styles/legend/Economicallyinactive1664Alln_4_2.png" /> 24600 - 31400<br />\
    <img src="styles/legend/Economicallyinactive1664Alln_4_3.png" /> 31400 - 56600<br />\
    <img src="styles/legend/Economicallyinactive1664Alln_4_4.png" /> 56600 - 79800<br />' });
var format_Economicallyinactive1664All_5 = new ol.format.GeoJSON();
var features_Economicallyinactive1664All_5 = format_Economicallyinactive1664All_5.readFeatures(json_Economicallyinactive1664All_5, 
            {dataProjection: 'EPSG:4326', featureProjection: 'EPSG:3857'});
var jsonSource_Economicallyinactive1664All_5 = new ol.source.Vector({
    attributions: ' ',
});
jsonSource_Economicallyinactive1664All_5.addFeatures(features_Economicallyinactive1664All_5);
var lyr_Economicallyinactive1664All_5 = new ol.layer.Vector({
                declutter: false,
                source:jsonSource_Economicallyinactive1664All_5, 
                style: style_Economicallyinactive1664All_5,
                popuplayertitle: 'Economically inactive - 16-64 All %',
                interactive: true,
    title: 'Economically inactive - 16-64 All %<br />\
    <img src="styles/legend/Economicallyinactive1664All_5_0.png" /> 20.3 - 20.3<br />\
    <img src="styles/legend/Economicallyinactive1664All_5_1.png" /> 20.3 - 23.4<br />\
    <img src="styles/legend/Economicallyinactive1664All_5_2.png" /> 23.4 - 25.8<br />\
    <img src="styles/legend/Economicallyinactive1664All_5_3.png" /> 25.8 - 28.2<br />\
    <img src="styles/legend/Economicallyinactive1664All_5_4.png" /> 28.2 - 33.2<br />' });

lyr_OpenStreetMap_0.setVisible(true);lyr_Localauthorityname_1.setVisible(true);lyr_Economicallyactive1664Unemployedn_2.setVisible(true);lyr_Economicallyactive1664Unemployed_3.setVisible(true);lyr_Economicallyinactive1664Alln_4.setVisible(true);lyr_Economicallyinactive1664All_5.setVisible(true);
var layersList = [lyr_OpenStreetMap_0,lyr_Localauthorityname_1,lyr_Economicallyactive1664Unemployedn_2,lyr_Economicallyactive1664Unemployed_3,lyr_Economicallyinactive1664Alln_4,lyr_Economicallyinactive1664All_5];
lyr_Localauthorityname_1.set('fieldAliases', {'fid': 'fid', 'CTYUA22CD': 'CTYUA22CD', 'CTYUA22NM': 'CTYUA22NM', 'CTYUA22NMW': 'CTYUA22NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LONG': 'LONG', 'LAT': 'LAT', 'GlobalID': 'GlobalID', 'Local authority': 'Local authority', 'Economically inactive - Aged 16-64: All people': 'Economically inactive - Aged 16-64: All people', 'Economically inactive - Aged 16-64: Males': 'Economically inactive - Aged 16-64: Males', 'Economically inactive - Aged 16-64: Females': 'Economically inactive - Aged 16-64: Females', 'Economically inactive - Aged 16-64- Student': 'Economically inactive - Aged 16-64- Student', 'Economically inactive - Aged 16-64- Looking after family/home': 'Economically inactive - Aged 16-64- Looking after family/home', 'Economically inactive - Aged 16-64- Long-term sick': 'Economically inactive - Aged 16-64- Long-term sick', 'Economically inactive - Aged 16-64- Retired': 'Economically inactive - Aged 16-64- Retired', 'Economically inactive - Aged 16-64 - Wants a job': 'Economically inactive - Aged 16-64 - Wants a job', 'Economically inactive - Aged 16-64 - Does not want a job': 'Economically inactive - Aged 16-64 - Does not want a job', 'Economically active - Aged 16-64 - Economically active': 'Economically active - Aged 16-64 - Economically active', 'Economically active - Aged 16-64 - In employment': 'Economically active - Aged 16-64 - In employment', 'Economically active - Aged 16-64 - Employees': 'Economically active - Aged 16-64 - Employees', 'Economically active - Aged 16-64 - Self Employed': 'Economically active - Aged 16-64 - Self Employed', 'Economically active - Aged 16-64 - Unemployed': 'Economically active - Aged 16-64 - Unemployed', });
lyr_Economicallyactive1664Unemployedn_2.set('fieldAliases', {'fid': 'fid', 'CTYUA22CD': 'CTYUA22CD', 'CTYUA22NM': 'CTYUA22NM', 'CTYUA22NMW': 'CTYUA22NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LONG': 'LONG', 'LAT': 'LAT', 'GlobalID': 'GlobalID', 'Local authority': 'Local authority', 'Economically inactive - Aged 16-64: All people': 'Economically inactive - Aged 16-64: All people', 'Economically inactive - Aged 16-64: Males': 'Economically inactive - Aged 16-64: Males', 'Economically inactive - Aged 16-64: Females': 'Economically inactive - Aged 16-64: Females', 'Economically inactive - Aged 16-64- Student': 'Economically inactive - Aged 16-64- Student', 'Economically inactive - Aged 16-64- Looking after family/home': 'Economically inactive - Aged 16-64- Looking after family/home', 'Economically inactive - Aged 16-64- Long-term sick': 'Economically inactive - Aged 16-64- Long-term sick', 'Economically inactive - Aged 16-64- Retired': 'Economically inactive - Aged 16-64- Retired', 'Economically inactive - Aged 16-64 - Wants a job': 'Economically inactive - Aged 16-64 - Wants a job', 'Economically inactive - Aged 16-64 - Does not want a job': 'Economically inactive - Aged 16-64 - Does not want a job', 'Economically active - Aged 16-64 - Economically active': 'Economically active - Aged 16-64 - Economically active', 'Economically active - Aged 16-64 - In employment': 'Economically active - Aged 16-64 - In employment', 'Economically active - Aged 16-64 - Employees': 'Economically active - Aged 16-64 - Employees', 'Economically active - Aged 16-64 - Self Employed': 'Economically active - Aged 16-64 - Self Employed', 'Economically active - Aged 16-64 - Unemployed': 'Economically active - Aged 16-64 - Unemployed', 'Economically inactive - Aged 16-64 (n)': 'Economically inactive - Aged 16-64 (n)', 'Aged 16-64 - Unemployed (n)': 'Aged 16-64 - Unemployed (n)', });
lyr_Economicallyactive1664Unemployed_3.set('fieldAliases', {'fid': 'fid', 'CTYUA22CD': 'CTYUA22CD', 'CTYUA22NM': 'CTYUA22NM', 'CTYUA22NMW': 'CTYUA22NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LONG': 'LONG', 'LAT': 'LAT', 'GlobalID': 'GlobalID', 'Local authority': 'Local authority', 'Economically inactive - Aged 16-64: All people': 'Economically inactive - Aged 16-64: All people', 'Economically inactive - Aged 16-64: Males': 'Economically inactive - Aged 16-64: Males', 'Economically inactive - Aged 16-64: Females': 'Economically inactive - Aged 16-64: Females', 'Economically inactive - Aged 16-64- Student': 'Economically inactive - Aged 16-64- Student', 'Economically inactive - Aged 16-64- Looking after family/home': 'Economically inactive - Aged 16-64- Looking after family/home', 'Economically inactive - Aged 16-64- Long-term sick': 'Economically inactive - Aged 16-64- Long-term sick', 'Economically inactive - Aged 16-64- Retired': 'Economically inactive - Aged 16-64- Retired', 'Economically inactive - Aged 16-64 - Wants a job': 'Economically inactive - Aged 16-64 - Wants a job', 'Economically inactive - Aged 16-64 - Does not want a job': 'Economically inactive - Aged 16-64 - Does not want a job', 'Economically active - Aged 16-64 - Economically active': 'Economically active - Aged 16-64 - Economically active', 'Economically active - Aged 16-64 - In employment': 'Economically active - Aged 16-64 - In employment', 'Economically active - Aged 16-64 - Employees': 'Economically active - Aged 16-64 - Employees', 'Economically active - Aged 16-64 - Self Employed': 'Economically active - Aged 16-64 - Self Employed', 'Economically active - Aged 16-64 - Unemployed': 'Economically active - Aged 16-64 - Unemployed', });
lyr_Economicallyinactive1664Alln_4.set('fieldAliases', {'fid': 'fid', 'CTYUA22CD': 'CTYUA22CD', 'CTYUA22NM': 'CTYUA22NM', 'CTYUA22NMW': 'CTYUA22NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LONG': 'LONG', 'LAT': 'LAT', 'GlobalID': 'GlobalID', 'Local authority': 'Local authority', 'Economically inactive - Aged 16-64: All people': 'Economically inactive - Aged 16-64: All people', 'Economically inactive - Aged 16-64: Males': 'Economically inactive - Aged 16-64: Males', 'Economically inactive - Aged 16-64: Females': 'Economically inactive - Aged 16-64: Females', 'Economically inactive - Aged 16-64- Student': 'Economically inactive - Aged 16-64- Student', 'Economically inactive - Aged 16-64- Looking after family/home': 'Economically inactive - Aged 16-64- Looking after family/home', 'Economically inactive - Aged 16-64- Long-term sick': 'Economically inactive - Aged 16-64- Long-term sick', 'Economically inactive - Aged 16-64- Retired': 'Economically inactive - Aged 16-64- Retired', 'Economically inactive - Aged 16-64 - Wants a job': 'Economically inactive - Aged 16-64 - Wants a job', 'Economically inactive - Aged 16-64 - Does not want a job': 'Economically inactive - Aged 16-64 - Does not want a job', 'Economically active - Aged 16-64 - Economically active': 'Economically active - Aged 16-64 - Economically active', 'Economically active - Aged 16-64 - In employment': 'Economically active - Aged 16-64 - In employment', 'Economically active - Aged 16-64 - Employees': 'Economically active - Aged 16-64 - Employees', 'Economically active - Aged 16-64 - Self Employed': 'Economically active - Aged 16-64 - Self Employed', 'Economically active - Aged 16-64 - Unemployed': 'Economically active - Aged 16-64 - Unemployed', 'Economically inactive - Aged 16-64 (n)': 'Economically inactive - Aged 16-64 (n)', 'Aged 16-64 - Unemployed (n)': 'Aged 16-64 - Unemployed (n)', });
lyr_Economicallyinactive1664All_5.set('fieldAliases', {'fid': 'fid', 'CTYUA22CD': 'CTYUA22CD', 'CTYUA22NM': 'CTYUA22NM', 'CTYUA22NMW': 'CTYUA22NMW', 'BNG_E': 'BNG_E', 'BNG_N': 'BNG_N', 'LONG': 'LONG', 'LAT': 'LAT', 'GlobalID': 'GlobalID', 'Local authority': 'Local authority', 'Economically inactive - Aged 16-64: All people': 'Economically inactive - Aged 16-64: All people', 'Economically inactive - Aged 16-64: Males': 'Economically inactive - Aged 16-64: Males', 'Economically inactive - Aged 16-64: Females': 'Economically inactive - Aged 16-64: Females', 'Economically inactive - Aged 16-64- Student': 'Economically inactive - Aged 16-64- Student', 'Economically inactive - Aged 16-64- Looking after family/home': 'Economically inactive - Aged 16-64- Looking after family/home', 'Economically inactive - Aged 16-64- Long-term sick': 'Economically inactive - Aged 16-64- Long-term sick', 'Economically inactive - Aged 16-64- Retired': 'Economically inactive - Aged 16-64- Retired', 'Economically inactive - Aged 16-64 - Wants a job': 'Economically inactive - Aged 16-64 - Wants a job', 'Economically inactive - Aged 16-64 - Does not want a job': 'Economically inactive - Aged 16-64 - Does not want a job', 'Economically active - Aged 16-64 - Economically active': 'Economically active - Aged 16-64 - Economically active', 'Economically active - Aged 16-64 - In employment': 'Economically active - Aged 16-64 - In employment', 'Economically active - Aged 16-64 - Employees': 'Economically active - Aged 16-64 - Employees', 'Economically active - Aged 16-64 - Self Employed': 'Economically active - Aged 16-64 - Self Employed', 'Economically active - Aged 16-64 - Unemployed': 'Economically active - Aged 16-64 - Unemployed', });
lyr_Localauthorityname_1.set('fieldImages', {'fid': 'TextEdit', 'CTYUA22CD': 'TextEdit', 'CTYUA22NM': 'TextEdit', 'CTYUA22NMW': 'TextEdit', 'BNG_E': 'Range', 'BNG_N': 'Range', 'LONG': 'TextEdit', 'LAT': 'TextEdit', 'GlobalID': 'TextEdit', 'Local authority': 'TextEdit', 'Economically inactive - Aged 16-64: All people': 'TextEdit', 'Economically inactive - Aged 16-64: Males': 'TextEdit', 'Economically inactive - Aged 16-64: Females': 'TextEdit', 'Economically inactive - Aged 16-64- Student': 'TextEdit', 'Economically inactive - Aged 16-64- Looking after family/home': 'TextEdit', 'Economically inactive - Aged 16-64- Long-term sick': 'TextEdit', 'Economically inactive - Aged 16-64- Retired': 'TextEdit', 'Economically inactive - Aged 16-64 - Wants a job': 'TextEdit', 'Economically inactive - Aged 16-64 - Does not want a job': 'TextEdit', 'Economically active - Aged 16-64 - Economically active': 'TextEdit', 'Economically active - Aged 16-64 - In employment': 'TextEdit', 'Economically active - Aged 16-64 - Employees': 'TextEdit', 'Economically active - Aged 16-64 - Self Employed': 'TextEdit', 'Economically active - Aged 16-64 - Unemployed': 'TextEdit', });
lyr_Economicallyactive1664Unemployedn_2.set('fieldImages', {'fid': 'TextEdit', 'CTYUA22CD': 'TextEdit', 'CTYUA22NM': 'TextEdit', 'CTYUA22NMW': 'TextEdit', 'BNG_E': 'Range', 'BNG_N': 'Range', 'LONG': 'TextEdit', 'LAT': 'TextEdit', 'GlobalID': 'TextEdit', 'Local authority': 'TextEdit', 'Economically inactive - Aged 16-64: All people': 'TextEdit', 'Economically inactive - Aged 16-64: Males': 'TextEdit', 'Economically inactive - Aged 16-64: Females': 'TextEdit', 'Economically inactive - Aged 16-64- Student': 'TextEdit', 'Economically inactive - Aged 16-64- Looking after family/home': 'TextEdit', 'Economically inactive - Aged 16-64- Long-term sick': 'TextEdit', 'Economically inactive - Aged 16-64- Retired': 'TextEdit', 'Economically inactive - Aged 16-64 - Wants a job': 'TextEdit', 'Economically inactive - Aged 16-64 - Does not want a job': 'TextEdit', 'Economically active - Aged 16-64 - Economically active': 'TextEdit', 'Economically active - Aged 16-64 - In employment': 'TextEdit', 'Economically active - Aged 16-64 - Employees': 'TextEdit', 'Economically active - Aged 16-64 - Self Employed': 'TextEdit', 'Economically active - Aged 16-64 - Unemployed': 'TextEdit', 'Economically inactive - Aged 16-64 (n)': 'Range', 'Aged 16-64 - Unemployed (n)': 'Range', });
lyr_Economicallyactive1664Unemployed_3.set('fieldImages', {'fid': 'TextEdit', 'CTYUA22CD': 'TextEdit', 'CTYUA22NM': 'TextEdit', 'CTYUA22NMW': 'TextEdit', 'BNG_E': 'Range', 'BNG_N': 'Range', 'LONG': 'TextEdit', 'LAT': 'TextEdit', 'GlobalID': 'TextEdit', 'Local authority': 'TextEdit', 'Economically inactive - Aged 16-64: All people': 'TextEdit', 'Economically inactive - Aged 16-64: Males': 'TextEdit', 'Economically inactive - Aged 16-64: Females': 'TextEdit', 'Economically inactive - Aged 16-64- Student': 'TextEdit', 'Economically inactive - Aged 16-64- Looking after family/home': 'TextEdit', 'Economically inactive - Aged 16-64- Long-term sick': 'TextEdit', 'Economically inactive - Aged 16-64- Retired': 'TextEdit', 'Economically inactive - Aged 16-64 - Wants a job': 'TextEdit', 'Economically inactive - Aged 16-64 - Does not want a job': 'TextEdit', 'Economically active - Aged 16-64 - Economically active': 'TextEdit', 'Economically active - Aged 16-64 - In employment': 'TextEdit', 'Economically active - Aged 16-64 - Employees': 'TextEdit', 'Economically active - Aged 16-64 - Self Employed': 'TextEdit', 'Economically active - Aged 16-64 - Unemployed': 'TextEdit', });
lyr_Economicallyinactive1664Alln_4.set('fieldImages', {'fid': 'TextEdit', 'CTYUA22CD': 'TextEdit', 'CTYUA22NM': 'TextEdit', 'CTYUA22NMW': 'TextEdit', 'BNG_E': 'Range', 'BNG_N': 'Range', 'LONG': 'TextEdit', 'LAT': 'TextEdit', 'GlobalID': 'TextEdit', 'Local authority': 'TextEdit', 'Economically inactive - Aged 16-64: All people': 'TextEdit', 'Economically inactive - Aged 16-64: Males': 'TextEdit', 'Economically inactive - Aged 16-64: Females': 'TextEdit', 'Economically inactive - Aged 16-64- Student': 'TextEdit', 'Economically inactive - Aged 16-64- Looking after family/home': 'TextEdit', 'Economically inactive - Aged 16-64- Long-term sick': 'TextEdit', 'Economically inactive - Aged 16-64- Retired': 'TextEdit', 'Economically inactive - Aged 16-64 - Wants a job': 'TextEdit', 'Economically inactive - Aged 16-64 - Does not want a job': 'TextEdit', 'Economically active - Aged 16-64 - Economically active': 'TextEdit', 'Economically active - Aged 16-64 - In employment': 'TextEdit', 'Economically active - Aged 16-64 - Employees': 'TextEdit', 'Economically active - Aged 16-64 - Self Employed': 'TextEdit', 'Economically active - Aged 16-64 - Unemployed': 'TextEdit', 'Economically inactive - Aged 16-64 (n)': 'Range', 'Aged 16-64 - Unemployed (n)': 'Range', });
lyr_Economicallyinactive1664All_5.set('fieldImages', {'fid': 'TextEdit', 'CTYUA22CD': 'TextEdit', 'CTYUA22NM': 'TextEdit', 'CTYUA22NMW': 'TextEdit', 'BNG_E': 'Range', 'BNG_N': 'Range', 'LONG': 'TextEdit', 'LAT': 'TextEdit', 'GlobalID': 'TextEdit', 'Local authority': 'TextEdit', 'Economically inactive - Aged 16-64: All people': 'TextEdit', 'Economically inactive - Aged 16-64: Males': 'TextEdit', 'Economically inactive - Aged 16-64: Females': 'TextEdit', 'Economically inactive - Aged 16-64- Student': 'TextEdit', 'Economically inactive - Aged 16-64- Looking after family/home': 'TextEdit', 'Economically inactive - Aged 16-64- Long-term sick': 'TextEdit', 'Economically inactive - Aged 16-64- Retired': 'TextEdit', 'Economically inactive - Aged 16-64 - Wants a job': 'TextEdit', 'Economically inactive - Aged 16-64 - Does not want a job': 'TextEdit', 'Economically active - Aged 16-64 - Economically active': 'TextEdit', 'Economically active - Aged 16-64 - In employment': 'TextEdit', 'Economically active - Aged 16-64 - Employees': 'TextEdit', 'Economically active - Aged 16-64 - Self Employed': 'TextEdit', 'Economically active - Aged 16-64 - Unemployed': 'TextEdit', });
lyr_Localauthorityname_1.set('fieldLabels', {'fid': 'hidden field', 'CTYUA22CD': 'hidden field', 'CTYUA22NM': 'hidden field', 'CTYUA22NMW': 'hidden field', 'BNG_E': 'hidden field', 'BNG_N': 'hidden field', 'LONG': 'hidden field', 'LAT': 'hidden field', 'GlobalID': 'hidden field', 'Local authority': 'inline label - visible with data', 'Economically inactive - Aged 16-64: All people': 'hidden field', 'Economically inactive - Aged 16-64: Males': 'hidden field', 'Economically inactive - Aged 16-64: Females': 'hidden field', 'Economically inactive - Aged 16-64- Student': 'hidden field', 'Economically inactive - Aged 16-64- Looking after family/home': 'hidden field', 'Economically inactive - Aged 16-64- Long-term sick': 'hidden field', 'Economically inactive - Aged 16-64- Retired': 'hidden field', 'Economically inactive - Aged 16-64 - Wants a job': 'hidden field', 'Economically inactive - Aged 16-64 - Does not want a job': 'hidden field', 'Economically active - Aged 16-64 - Economically active': 'hidden field', 'Economically active - Aged 16-64 - In employment': 'hidden field', 'Economically active - Aged 16-64 - Employees': 'hidden field', 'Economically active - Aged 16-64 - Self Employed': 'hidden field', 'Economically active - Aged 16-64 - Unemployed': 'hidden field', });
lyr_Economicallyactive1664Unemployedn_2.set('fieldLabels', {'fid': 'hidden field', 'CTYUA22CD': 'hidden field', 'CTYUA22NM': 'hidden field', 'CTYUA22NMW': 'hidden field', 'BNG_E': 'hidden field', 'BNG_N': 'hidden field', 'LONG': 'hidden field', 'LAT': 'hidden field', 'GlobalID': 'hidden field', 'Local authority': 'hidden field', 'Economically inactive - Aged 16-64: All people': 'hidden field', 'Economically inactive - Aged 16-64: Males': 'hidden field', 'Economically inactive - Aged 16-64: Females': 'hidden field', 'Economically inactive - Aged 16-64- Student': 'hidden field', 'Economically inactive - Aged 16-64- Looking after family/home': 'hidden field', 'Economically inactive - Aged 16-64- Long-term sick': 'hidden field', 'Economically inactive - Aged 16-64- Retired': 'hidden field', 'Economically inactive - Aged 16-64 - Wants a job': 'hidden field', 'Economically inactive - Aged 16-64 - Does not want a job': 'hidden field', 'Economically active - Aged 16-64 - Economically active': 'hidden field', 'Economically active - Aged 16-64 - In employment': 'hidden field', 'Economically active - Aged 16-64 - Employees': 'hidden field', 'Economically active - Aged 16-64 - Self Employed': 'hidden field', 'Economically active - Aged 16-64 - Unemployed': 'hidden field', 'Economically inactive - Aged 16-64 (n)': 'hidden field', 'Aged 16-64 - Unemployed (n)': 'no label', });
lyr_Economicallyactive1664Unemployed_3.set('fieldLabels', {'fid': 'hidden field', 'CTYUA22CD': 'hidden field', 'CTYUA22NM': 'hidden field', 'CTYUA22NMW': 'hidden field', 'BNG_E': 'hidden field', 'BNG_N': 'hidden field', 'LONG': 'hidden field', 'LAT': 'hidden field', 'GlobalID': 'hidden field', 'Local authority': 'hidden field', 'Economically inactive - Aged 16-64: All people': 'hidden field', 'Economically inactive - Aged 16-64: Males': 'hidden field', 'Economically inactive - Aged 16-64: Females': 'hidden field', 'Economically inactive - Aged 16-64- Student': 'hidden field', 'Economically inactive - Aged 16-64- Looking after family/home': 'hidden field', 'Economically inactive - Aged 16-64- Long-term sick': 'hidden field', 'Economically inactive - Aged 16-64- Retired': 'hidden field', 'Economically inactive - Aged 16-64 - Wants a job': 'hidden field', 'Economically inactive - Aged 16-64 - Does not want a job': 'hidden field', 'Economically active - Aged 16-64 - Economically active': 'hidden field', 'Economically active - Aged 16-64 - In employment': 'hidden field', 'Economically active - Aged 16-64 - Employees': 'hidden field', 'Economically active - Aged 16-64 - Self Employed': 'hidden field', 'Economically active - Aged 16-64 - Unemployed': 'no label', });
lyr_Economicallyinactive1664Alln_4.set('fieldLabels', {'fid': 'hidden field', 'CTYUA22CD': 'hidden field', 'CTYUA22NM': 'hidden field', 'CTYUA22NMW': 'hidden field', 'BNG_E': 'hidden field', 'BNG_N': 'hidden field', 'LONG': 'hidden field', 'LAT': 'hidden field', 'GlobalID': 'hidden field', 'Local authority': 'hidden field', 'Economically inactive - Aged 16-64: All people': 'hidden field', 'Economically inactive - Aged 16-64: Males': 'hidden field', 'Economically inactive - Aged 16-64: Females': 'hidden field', 'Economically inactive - Aged 16-64- Student': 'hidden field', 'Economically inactive - Aged 16-64- Looking after family/home': 'hidden field', 'Economically inactive - Aged 16-64- Long-term sick': 'hidden field', 'Economically inactive - Aged 16-64- Retired': 'hidden field', 'Economically inactive - Aged 16-64 - Wants a job': 'hidden field', 'Economically inactive - Aged 16-64 - Does not want a job': 'hidden field', 'Economically active - Aged 16-64 - Economically active': 'hidden field', 'Economically active - Aged 16-64 - In employment': 'hidden field', 'Economically active - Aged 16-64 - Employees': 'hidden field', 'Economically active - Aged 16-64 - Self Employed': 'hidden field', 'Economically active - Aged 16-64 - Unemployed': 'hidden field', 'Economically inactive - Aged 16-64 (n)': 'no label', 'Aged 16-64 - Unemployed (n)': 'hidden field', });
lyr_Economicallyinactive1664All_5.set('fieldLabels', {'fid': 'hidden field', 'CTYUA22CD': 'hidden field', 'CTYUA22NM': 'hidden field', 'CTYUA22NMW': 'hidden field', 'BNG_E': 'hidden field', 'BNG_N': 'hidden field', 'LONG': 'hidden field', 'LAT': 'hidden field', 'GlobalID': 'hidden field', 'Local authority': 'hidden field', 'Economically inactive - Aged 16-64: All people': 'no label', 'Economically inactive - Aged 16-64: Males': 'hidden field', 'Economically inactive - Aged 16-64: Females': 'hidden field', 'Economically inactive - Aged 16-64- Student': 'hidden field', 'Economically inactive - Aged 16-64- Looking after family/home': 'hidden field', 'Economically inactive - Aged 16-64- Long-term sick': 'hidden field', 'Economically inactive - Aged 16-64- Retired': 'hidden field', 'Economically inactive - Aged 16-64 - Wants a job': 'hidden field', 'Economically inactive - Aged 16-64 - Does not want a job': 'hidden field', 'Economically active - Aged 16-64 - Economically active': 'hidden field', 'Economically active - Aged 16-64 - In employment': 'hidden field', 'Economically active - Aged 16-64 - Employees': 'hidden field', 'Economically active - Aged 16-64 - Self Employed': 'hidden field', 'Economically active - Aged 16-64 - Unemployed': 'hidden field', });
lyr_Economicallyinactive1664All_5.on('precompose', function(evt) {
    evt.context.globalCompositeOperation = 'normal';
});